export default [
    {
        pImg: "img1.jpg",
        postImg: "img1.jpg",
        postImg1: "img2.jpg",
        postImg2: "img3.jpg",
        postImg3: "img4.jpg",
        likes: "24",
        username: "Luffy79",
        Pdate: "August 22",
    },
    {
        pImg: "img2.jpg",
        postImg: "img4.jpg",
        postImg1: "img2.jpg",
        postImg2: "img3.jpg",
        postImg3: "img4.jpg",
        likes: "1,408",
        username: "Tanjiro567",
        Pdate: "August 7",
    },
    {
        pImg: "img4.jpg",
        postImg: "img3.jpg",
        postImg1: "img2.jpg",
        postImg2: "img3.jpg",
        postImg3: "img4.jpg",
        likes: "24,008",
        username: "urokaodaki777",
        Pdate: "August 2",
    },
]